language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

#install: composer install --dev
before_install:
    - composer self-update

before_script:
  - composer update --prefer-source --prefer-stable $PREFER_LOWEST

script: phpunit --coverage-text

cache:
  directories:
    - $COMPOSER_CACHE_DIR
